FROM idkidr/coder-base:centos

# Run everything as root
USER root

# Install required dependencies
RUN dnf install --assumeyes \
   python38-devel libffi-devel

# Install jupyter
RUN pip3.8 install jupyter-core==4.7.1 packaging && \
    pip3.8 install jupyterlab

# Set back to coder user
USER coder
